# SESI 9
Descriptive Statistics

In [1]:
!pip install scipy

You should consider upgrading via the '/Users/firdausnutrihadi/opt/anaconda3/bin/python -m pip install --upgrade pip' command.


In [3]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [9]:
x = [8.0,1,2.5,4,28.0]
x_with_nan = [8.0,1,2.5,math.nan,4,28.0]
print(x)
print(x_with_nan)

[8.0, 1, 2.5, 4, 28.0]
[8.0, 1, 2.5, nan, 4, 28.0]


In [12]:
y, y_with_nan = np.array(x), np.array(x_with_nan)
z,z_with_nan = pd.Series(x), pd.Series(x_with_nan)
print(y)
print(y_with_nan)
print(z_with_nan)

[ 8.   1.   2.5  4.  28. ]
[ 8.   1.   2.5  nan  4.  28. ]
0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64


## Measures of Central Tendency

In [13]:
#Mean

In [15]:
mean_=sum(x)/len(x)
mean_

8.7

In [16]:
mean_ = statistics.mean(x)
mean_

8.7

In [17]:
mean_ = statistics.mean(x_with_nan)
mean_

nan

In [18]:
mean_=np.mean(x)
mean_

8.7

In [20]:
mean_=np.mean(x_with_nan)
mean_

nan

In [21]:
y.mean()

8.7

In [22]:
y_with_nan.mean()

nan

In [23]:
z.mean()

8.7

In [24]:
z_with_nan.mean()

8.7

In [25]:
#Weighted Mean

In [26]:
x=[8.0, 1, 2.5, 4, 28.0]
w=[0.1,0.2,0.3,0.25,0.15]
w=np.array(w)
w

array([0.1 , 0.2 , 0.3 , 0.25, 0.15])

In [27]:
np.average(y,weights=w)

6.95

In [28]:
np.average(z,weights=w)

6.95

In [29]:
#harmonic mean

In [43]:
statistics.harmonic_mean(y)

2.7613412228796843

In [45]:
scipy.stats.hmean(y)

2.7613412228796843

In [48]:
#geomteric mean

In [46]:
scipy.stats.gmean(z)

4.67788567485604

In [47]:
scipy.stats.gmean(y)

4.67788567485604

In [49]:
#MEDIAN

In [50]:
x=[8.0, 1, 2.5, 4, 28.0]

In [53]:
statistics.median_low(x[:-1])

2.5

In [54]:
statistics.median_high(x[:-1])

4

In [55]:
statistics.median(x[:-1])

3.25

In [56]:
statistics.median(x_with_nan)

6.0

In [57]:
#numpy

In [60]:
np.median(y)

4.0

In [61]:
np.median(y[:-1])

3.25

In [62]:
#modus

In [63]:
u = [2,3,2,8,12]
v = [12,15,12,15,21,15,12]

In [65]:
u

[2, 3, 2, 8, 12]

In [66]:
v

[12, 15, 12, 15, 21, 15, 12]

In [69]:
statistics.mode(u)

2

In [70]:
statistics.mode(v)

12

In [71]:
u,v=np.array(u), np.array(v)

In [72]:
scipy.stats.mode(u)

ModeResult(mode=array([2]), count=array([2]))

In [73]:
scipy.stats.mode(v)

ModeResult(mode=array([12]), count=array([3]))

In [75]:
u,v,w = pd.Series(u), pd.Series(v), pd.Series([2,2,math.nan])

In [79]:
u.mode()

0    2
dtype: int64

In [80]:
v.mode()

0    12
1    15
dtype: int64

In [81]:
w.mode()

0    2.0
dtype: float64

## Measures of Variability

In [84]:
#variance

In [85]:
x

[8.0, 1, 2.5, 4, 28.0]

In [86]:
statistics.variance(x)

123.2

In [87]:
np.var(y, ddof=1)

123.19999999999999

In [88]:
z.var(ddof=1)

123.19999999999999

In [89]:
#std dev

In [90]:
statistics.stdev(x)

11.099549540409287

In [91]:
np.std(y,ddof=1)

11.099549540409285

In [92]:
z.std(ddof=1)

11.099549540409285

In [93]:
#skewnes

In [94]:
x

[8.0, 1, 2.5, 4, 28.0]

In [95]:
y

array([ 8. ,  1. ,  2.5,  4. , 28. ])

In [96]:
scipy.stats.skew(y, bias=False)

1.9470432273905927

In [97]:
z.skew()

1.9470432273905924

In [98]:
z_with_nan.skew()

1.9470432273905924

In [99]:
#percentiles

In [100]:
x=[-5.0,-1.1,0.1, 2.0, 8.0,12.0,21.0, 25.8,41.0]

In [102]:
statistics.quantiles(x, n=2)

[8.0]

In [103]:
y = np.array(x)

In [104]:
np.percentile(y, 5)#urutan 5%

-3.44

In [105]:
np.percentile(y, 95) #urutan 95%

34.919999999999995

In [107]:
np.percentile(y, [25,50,75]) #urutan 25%,50%,75%

array([ 0.1,  8. , 21. ])

In [108]:
z = pd.Series(y)

In [109]:
z.quantile(0.5)

8.0

In [110]:
z.quantile(0.05)

-3.44

In [112]:
z.quantile(.25)

0.1

In [114]:
z.quantile([0.25,0.50,0.75])

0.25     0.1
0.50     8.0
0.75    21.0
dtype: float64

In [115]:
#range

In [116]:
np.ptp(x)

46.0

In [117]:
np.ptp(y)

46.0

In [118]:
np.ptp(z)

46.0