# NUMPY

In [1]:
import numpy as np

In [12]:
firstArray = np.array([[1,2,3,4],[2,3,4,5]])

In [14]:
print(firstArray[0])

[1 2 3 4]


In [15]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [18]:
np.ones(3)

array([1., 1., 1.])

In [22]:
np.empty(4)

array([-2.68156159e+154, -1.29074424e-231,  9.88131292e-324,
        2.78134232e-309])

In [24]:
np.arange(1,30,6)

array([ 1,  7, 13, 19, 25])

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [27]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr[1]

2

In [30]:
np.append(arr,[1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2])

In [40]:
np.append([1,2],arr)

array([1, 2, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.delete(arr,5)

array([1, 2, 3, 4, 5, 7, 8, 9])

In [44]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2])

In [45]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2])

In [46]:
np.sort(arr)

array([1, 1, 2, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
array_example = np.array([[[0, 1, 2, 3],
                           [0, 1, 2, 3]],
                          
                          [[0, 1, 2, 3],
                          [0, 1, 2, 3]]
                         
                          ])

In [73]:
array_example.ndim

3

In [74]:
print(array_example)

[[[0 1 2 3]
  [0 1 2 3]]

 [[0 1 2 3]
  [0 1 2 3]]]


In [75]:
array_example.size

16

In [76]:
array_example.shape

(2, 2, 4)

In [85]:
a = np.arange(12)

In [86]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [87]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [93]:
a.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [94]:
a = np.array([1,2,3,4,5,6])

In [95]:
a

array([1, 2, 3, 4, 5, 6])

In [98]:
a.shape

(6,)

In [100]:
a2 = a[np.newaxis,:]

In [101]:
a2

array([[1, 2, 3, 4, 5, 6]])

In [102]:
a2.sum()

21

In [104]:
a2.sum(axis=1)

array([21])