# Sesi 4
numpy

In [1]:
import numpy as np

In [2]:
firstArray = np.array([1,2,3,4])

In [3]:
firstArray

array([1, 2, 3, 4])

In [4]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [5]:
np.ones((6,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
np.empty((6,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,10,3)

array([1, 4, 7])

## Add, Remove, Sort

In [10]:
arr = np.array([1,2,3,4,5,6,7])

In [11]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
arr = np.append(arr, [1,2])

In [13]:
arr

array([1, 2, 3, 4, 5, 6, 7, 1, 2])

In [14]:
np.delete(arr,[1])

array([1, 3, 4, 5, 6, 7, 1, 2])

In [15]:
np.sort(arr)

array([1, 1, 2, 2, 3, 4, 5, 6, 7])

In [16]:
array_example = np.array([1,2,3,4,5,6,7])

In [17]:
array_example

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
array_example = np.array([[[1,2,3,4,5],
                           [1,2,3,4,5]],
                          
                          [[1,2,3,4,5],
                           [1,2,3,4,5]],
                          
                          [[1,2,3,4,5],
                           [1,2,3,4,5]]])

In [19]:
array_example

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [20]:
array_example.ndim

3

In [21]:
array_example.shape

(3, 2, 5)

In [22]:
array_example.size

30

In [23]:
arr = np.arange(6)

In [24]:
arr

array([0, 1, 2, 3, 4, 5])

In [25]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [26]:
arr

array([0, 1, 2, 3, 4, 5])

In [27]:
arr.shape

(6,)

In [28]:
arr2 = arr[np.newaxis]

In [29]:
arr2

array([[0, 1, 2, 3, 4, 5]])

In [30]:
arr2.shape

(1, 6)

In [31]:
arr3=arr[:,np.newaxis]

In [32]:
arr3

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [33]:
arr3.shape

(6, 1)

In [34]:
arr2

array([[0, 1, 2, 3, 4, 5]])

In [35]:
arr2.sum()

15

In [36]:
arr2.min()

0

## Matrices

In [37]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [38]:
np.random.random((5,2))

array([[0.61558895, 0.65437689],
       [0.01386006, 0.42090202],
       [0.58015088, 0.19518656],
       [0.21653184, 0.37804343],
       [0.83730511, 0.65937459]])

In [39]:
data = np.array([[1,2],[3,4]])

In [40]:
data

array([[1, 2],
       [3, 4]])

In [41]:
ones = np.ones((2,2))

In [42]:
ones

array([[1., 1.],
       [1., 1.]])

In [43]:
data * ones

array([[1., 2.],
       [3., 4.]])

In [44]:
data + ones

array([[2., 3.],
       [4., 5.]])

In [45]:
data = np.array([[1,2],[3,4],[5,6]])

In [46]:
data[1]

array([3, 4])

In [47]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
data[0]

array([1, 2])

In [49]:
data[0,1]

2

In [50]:
data[1,0]

3

In [51]:
data[0:1]

array([[1, 2]])

In [52]:
data[0:2]

array([[1, 2],
       [3, 4]])

In [54]:
data[0:2].shape

(2, 2)